import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { EdgeStoreProvider } from '@/lib/edgestore'

import { DialogProvider } from '@/providers/DialogProvider'
import { ThemeProvider } from '@/providers/ThemeProvider'
import { Toaster } from '@/components/ui/sonner'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'E-Commerce',
  description: 'Generated by create next app',
  icons: {
    icon: {
      url: '/logo.png',
      href: '/logo.png',
    },
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl={'/'}>
      <html
        lang="en"
        suppressHydrationWarning={true}
      >
        <body className={inter.className}>
          <ThemeProvider
            attribute={'class'}
            defaultTheme={'system'}
            enableSystem
            disableTransitionOnChange
          >
            <EdgeStoreProvider>
              <Toaster />
              <DialogProvider />
              {children}
            </EdgeStoreProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
